import { StepLabel } from '../../components/StepLabel/StepLabel'
import { AboutHero } from './components/AboutHero'
import { ModuleBridge } from './components/ModuleBridge'
import './AboutPage.css'

const OBJETIVOS_ESPECIFICOS = [
  'Identificar las variables físicas que determinan la trayectoria de la pelota en el lanzamiento a canasta.',
  'Representar geométrica y técnicamente el lanzamiento mediante sistemas de coordenadas, construcciones geométricas y diferentes vistas del sistema.',
  'Analizar el gesto de lanzamiento desde una perspectiva biomecánica, identificando los principales factores que no quedan representados en el modelo físico simplificado.',
  'Desarrollar y validar un modelo de simulación que permita estudiar las variables de lanzamiento sobre la trayectoria, la eficacia y los márgenes de error del tiro.',
  'Incorporar y evaluar un modelo de aprendizaje automático basado en un algoritmo como método complementario al modelo físico, comparando su capacidad para clasificar los lanzamientos favorables y desfavorables.',
]

/**
 * "Sobre el proyecto": contenido real de la memoria escrita
 * (public/memoria-tiro-a-canasta.pdf) — resumen, pregunta de investigación y
 * objetivos son los del propio trabajo, no un texto redactado aparte para
 * la web. El puente a los módulos (ModuleBridge) es la pieza original de
 * esta página: conecta cada apartado del documento con su módulo
 * interactivo correspondiente.
 */
export function AboutPage() {
  return (
    <div className="about-page">
      <AboutHero />

      <div className="about-page__content">
        <section>
          <StepLabel step={1}>Resumen</StepLabel>
          <p className="about-page__prose">
            Este trabajo desarrolla un laboratorio virtual interactivo para estudiar el tiro a canasta mediante
            modelos físicos y geométricos. A partir de un modelo basado en el movimiento parabólico, se analiza cómo
            variables como la velocidad inicial, el ángulo, la altura de liberación y la distancia al aro influyen en
            la trayectoria y en la eficacia del lanzamiento. El modelo físico se complementa con una representación
            geométrica y técnica que permite estudiar la relación espacial entre el balón y el aro. Mediante
            diferentes simulaciones se observa que la eficacia no depende de una única variable, sino de la
            combinación de las condiciones iniciales, y que algunas configuraciones presentan mayor tolerancia ante
            pequeñas variaciones. Además, se incorpora un modelo de aprendizaje automático basado en k-NN para
            clasificar nuevas configuraciones a partir de los resultados obtenidos mediante simulación.
          </p>
          <p className="about-page__prose about-page__prose--muted">
            <em>Abstract — </em>This research project presents an interactive virtual laboratory for analysing
            basketball shooting through physical and geometric modelling. Simulations show that successful shooting
            depends on the interaction between several initial conditions rather than a single variable, and that
            some configurations are more tolerant to small variations. A k-Nearest Neighbors (k-NN) model is also
            incorporated to classify shooting configurations generated by the physical model.
          </p>
          <p className="about-page__keywords">
            Palabras clave: tiro a canasta · modelización física · geometría · simulación · inteligencia artificial
          </p>
        </section>

        <section>
          <StepLabel step={2}>Pregunta de investigación</StepLabel>
          <blockquote className="about-page__question">
            ¿Cómo puede modelizarse y simularse el tiro a canasta mediante modelos físicos y geométricos apoyados en
            herramientas de inteligencia artificial para analizar la influencia de sus principales variables sobre la
            eficacia del lanzamiento y su margen de error?
          </blockquote>

          <div className="about-page__objectives">
            <h3>Objetivo general</h3>
            <p className="about-page__prose">
              Desarrollar una experiencia interactiva de simulación del tiro en baloncesto que integre modelos
              físicos, geométricos, incorporando la biomecánica y la inteligencia artificial como elementos
              complementarios para visualizar y comprender los factores que determinan la eficacia del lanzamiento.
            </p>
            <h3>Objetivos específicos</h3>
            <ol className="about-page__objectives-list">
              {OBJETIVOS_ESPECIFICOS.map((objective) => (
                <li key={objective}>{objective}</li>
              ))}
            </ol>
          </div>
        </section>

        <ModuleBridge />

        <section className="about-page__download">
          <StepLabel step={4}>La memoria completa</StepLabel>
          <p className="about-page__prose">
            Este laboratorio es la mitad interactiva del trabajo. La otra mitad — el marco teórico, el desarrollo
            completo del modelo, la metodología de trabajo con IA y las conclusiones — está en la memoria escrita.
          </p>
          <a className="about-page__download-button" href="/memoria-tiro-a-canasta.pdf" target="_blank" rel="noreferrer">
            Descargar la memoria completa (PDF)
          </a>
        </section>
      </div>
    </div>
  )
}
